In [3]:
import numpy as np #numerical python
#1d -- a[5]
#2d --a[2][4]
#creating an array
lst=[1,2,3,4]
arr1=np.array(lst)
arr1

array([1, 2, 3, 4])

In [5]:
## a range
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#matrix
arr3=np.ones(2)
arr3
arr4=np.zeros(7)
arr4

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr5=np.linspace(1,10,20)
arr5

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [10]:
#2d array --matrix -- m x n
#m=rows
#n=columns
arr6=np.zeros((2,3))
arr6


array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#reshape
import numpy as np
arr5=np.arange(1,31).reshape(6,5)
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
##
arr6=np.random.randint(1,4,18) #its range in 1 to 4 and 18 numbers will be generate
arr6

array([1, 1, 2, 1, 1, 1, 3, 3, 3, 2, 2, 3, 2, 3, 1, 1, 1, 3])

In [14]:
arr7=np.random.randint(1,10,(2,6)) #(2,6) is used to create a 2d array of random numbers
arr7

array([[3, 6, 1, 6, 6, 3],
       [8, 5, 5, 7, 2, 4]])

In [19]:
arr8=np.random.randint(1,60,(6,5))
arr8

array([[50, 55,  1, 16, 20],
       [ 3, 28, 29, 48, 24],
       [41, 54, 47, 22, 15],
       [ 1, 39, 39, 34,  5],
       [16, 31, 35, 16, 50],
       [45, 18, 57, 54,  3]])

In [17]:
arr7=np.arange(60).reshape((12,5))
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [20]:
arr7.shape # it tells about the number of rows and columns

(12, 5)

In [21]:
arr7.dtype #  it tells about the data type

dtype('int32')

In [22]:
arr7.ndim  #  it tells about the dimensation

2

In [23]:
arr7.size #  it tells about size of an array

60

In [24]:
arr7.flatten() #  it convert 2d into 1d 
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [26]:
arr8=arr7.T # it helps to transpose the previous array in another 
arr8.shape

(5, 12)

In [28]:
#accessing and slicing in array
arr8=np.arange(1,10)
arr8

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr8[6]=600 # insert a new input
arr8

array([  1,   2,   3,   4,   5,   6, 600,   8,   9])

In [31]:
arr8[1:5] # this is slicing of a list


array([2, 3, 4, 5])

In [37]:
arr7=np.arange(60).reshape((12,5))
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [34]:
#2d- array --[row start:end:row skip,columns start:stop:skip]
arr7[0]


array([0, 1, 2, 3, 4])

In [35]:
arr7[0:6]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
arr7[0:6,0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21],
       [25, 26]])

In [53]:
arr4=np.random.randint(1.0,34.0,(2,6))
arr4

array([[ 2, 11, 20, 28, 33, 25],
       [ 4,  3, 12,  8, 15, 21]])

In [41]:
arr7[-5:-1]
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [43]:
#creating 3d
arr=np.random.randint(1,10,(2,3,7)) #3d array     2->table,3->rows,7->columns
arr

array([[[4, 1, 5, 6, 4, 9, 1],
        [5, 2, 5, 7, 9, 7, 2],
        [8, 4, 1, 4, 6, 2, 8]],

       [[3, 5, 6, 2, 6, 9, 3],
        [2, 3, 3, 6, 5, 8, 2],
        [7, 9, 1, 8, 7, 8, 3]]])

In [62]:
arr10=np.arange(60).reshape((2,3,10)) #reshape values must be multiple and equals to arange value
arr10

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [64]:
arr10=np.arange(625).reshape((25,5,5)) #reshape values must be multiple and equals to arange value
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]],

       [[125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [1

In [66]:
## 3d array --[table start:end :skip,row start:end:skip,columns start:end:skip]
arr[0:2,0:6,0:3]


array([[[4, 1, 5],
        [5, 2, 5],
        [8, 4, 1]],

       [[3, 5, 6],
        [2, 3, 3],
        [7, 9, 1]]])

In [67]:
arr=np.arange(60).reshape((3,2,10))
arr

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

In [74]:
arr[0:10,0:2,2:3]

array([[[ 2],
        [12]],

       [[22],
        [32]],

       [[42],
        [52]]])