In [1]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 29],
    'Salary': [50000, 60000, 55000, 52000, 57000],
    'Department': ['HR', 'Finance', 'IT', 'IT', 'Finance']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)

# Filter rows where Age is greater than 30
filtered_df = df[df['Age'] > 30]
print("\nFiltered DataFrame (Age > 30):")
print(filtered_df)

# Group by Department and calculate the average Salary
grouped_df = df.groupby('Department')['Salary'].mean().reset_index()
grouped_df.rename(columns={'Salary': 'Average Salary'}, inplace=True)
print("\nAverage Salary by Department:")
print(grouped_df)

# Save the grouped DataFrame to a CSV file
output_file = 'average_salary_by_department.csv'
grouped_df.to_csv(output_file, index=False)
print(f"\nGrouped data saved to {output_file}")


Original DataFrame:
      Name  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000    Finance
2  Charlie   35   55000         IT
3    David   40   52000         IT
4      Eve   29   57000    Finance

Filtered DataFrame (Age > 30):
      Name  Age  Salary Department
2  Charlie   35   55000         IT
3    David   40   52000         IT

Average Salary by Department:
  Department  Average Salary
0    Finance         58500.0
1         HR         50000.0
2         IT         53500.0

Grouped data saved to average_salary_by_department.csv


In [2]:
import numpy as np

# Create NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform basic operations
sum_array = array1 + array2
diff_array = array1 - array2
prod_array = array1 * array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Sum of Arrays:", sum_array)
print("Difference of Arrays:", diff_array)
print("Product of Arrays:", prod_array)

# Generate a range of numbers
range_array = np.arange(1, 10, 2)  # Start at 1, end at 10 (exclusive), step size of 2
print("\nGenerated Range Array:", range_array)

# Calculate statistical measures
mean_value = np.mean(array1)
median_value = np.median(array1)
std_dev = np.std(array1)

print("\nStatistical Measures for Array 1:")
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)

# Create a 2D array
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array2D)

# Perform operations on 2D array
transpose_array = np.transpose(array2D)
print("\nTransposed 2D Array:")
print(transpose_array)


Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Sum of Arrays: [6 6 6 6 6]
Difference of Arrays: [-4 -2  0  2  4]
Product of Arrays: [5 8 9 8 5]

Generated Range Array: [1 3 5 7 9]

Statistical Measures for Array 1:
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed 2D Array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
